---
title: "Problem Set 1"
output: html_notebook
---

Primero preparamos el espacio de trabajo y cargamos las librerías a utilizar:
```{r, results='hide'}
rm(list = ls())
install.packages("kableExtra") ## puedo usar este paquete para hacer tablas lindas, el enlace con el tutorial esta en week-04.R de la complementaria del 1ro de septiembre.
library(pacman)
library(rvest, tidyverse, kableExtra)

```


# Punto 1: Datos

## Collecting the Data
```{r}
url <- "https://ignaciomsarmiento.github.io/GEIH2018_sample/pages/geih_page_1.html"
browseURL(url)
tablas <- html %>%
  html_elements("table") %>%
  html_table()

url_test <- paste0("https://ignaciomsarmiento.github.io/GEIH2018_sample/pages/geih_page_", 1:10, ".html")
geih <- data.frame()
for (url in url_test) {
  print(url)
  source_table <- read_html(url) %>%
    html_table()
  temp <- as.data.frame(source_table)
  print(nrow(temp))
  geih <- rbind(geih, temp)
}
```
```{r cars}
write.table(x = geih,file = "~/Downloads/geih_full.csv")
```


# Complementaria Eduardo
```{r, }

df = mtcars %>% mutate(i_mpg = ifelse(mpg>0, "aumenta","disminuye"), modelo=rownames(.))
summary(df)
df
df %>% head() %>% kbl()
```
La base de datos **df** tiene las siguientes variables `r colnames(df)` y el valor mínimo de la variable **mpg** es `r min(df$mpg)`, y el modelo Mazda RX4 _`r df$i_mpg[df$modelo=="Mazda RX4"]`_
