---
title: "Problem Set 1"
author: "Karol Gutiérrez (201816712), Gustavo A. Castillo Alvarez (201812166)"
output:
  pdf_document: default
  html_notebook: default
  html_document:
    theme: lumen
    highlight: tango
    toc: yes
    toc_float: yes
    df_print: paged
urlcolor: blue
linkcolor: red
---

Primero preparamos el espacio de trabajo y cargamos las librerías a utilizar:
```{r, results='hide'}
rm(list = ls())

# Package names
packages <- c("pacman", "rvest", "dplyr", "tidyr", "caret", "kableExtra", "tidyverse")

# Install packages not yet installed
#installed.packages <- packages %in% rownames(installed.packages())
#if (any(installed.packages()== FALSE)){
#  install.packages(packages[!installed.packages])
#}

# Packages loading





```


# Punto 1: Datos

## Collecting the Data
```{r eval=FALSE}
url_test <- paste0("https://ignaciomsarmiento.github.io/GEIH2018_sample/pages/geih_page_", 1:10, ".html")
geih <- data.frame()
for (url in url_test) {
  print(url)
  source_table <- read_html(url) %>%
    html_table()
  temp <- as.data.frame(source_table)
  print(nrow(temp))
  geih <- rbind(geih, temp)
}
```

```{r karol, eval=FALSE}
##(a)	Data acquisition

rm(list = ls())
pacman::p_load(rvest, dplyr, tidy, caret, kableExtra, tidyverse)
url_test <- paste0("https://ignaciomsarmiento.github.io/GEIH2018_sample/pages/geih_page_", 1:10, ".html")
geih <- data.frame()
for (url in url_test) {
  print(url)
  source_table <- read_html(url) %>%
    html_table()
  temp <- as.data.frame(source_table)
  print(nrow(temp))
  geih <- rbind(geih, temp)
}
view(geih)


##(b)	Data Cleaning 
#seleccionamos las variables relevantes para nuestro estudio
#seleccionamos todas las variables relevantes

geih2018 <- geih %>% select(ingtotob, age, p6210, dsi, maxEducLevel,estrato1)

geihmodificado <- geih2018 %>% filter(age >=18)
view(geihmodificado)

baselista <- geihmodificado %>% filter(dsi != "0")
view(baselista)

base2018 <- na.omit(baselista)
```


# Punto 2: Age-earnings profile

```{r}
df <- df %>% 
  mutate(age_sqr = age * age)

model2 <- lm(df$ingtotob~df$age+df$age_sqr)
shortgeih <- geih %>% filter(age>=18, dsi==0)
model3 <- lm(shortgeih$ingtot~shortgeih$age+(shortgeih %>% mutate(age2 = age*age))$age2)
stargazer(model2, model3, type = "text")

```

# Punto 3: The gender earnings gap


$$
\log(ingtotob)=\beta_1+\beta_2 sex+u
$$

```{r}
df$female <- ifelse(df$sex==0, 1, 0)
df <- df %>%
  mutate(l_y=log(ingtotob))

```



# Complementaria Eduardo
```{r}

df = mtcars %>% mutate(i_mpg = ifelse(mpg>0, "aumenta","disminuye"), modelo=rownames(.))
summary(df)
df
df %>% head() %>% kbl()

install.packages("kableExtra") ## puedo usar este paquete para hacer tablas lindas, el enlace con el tutorial esta en week-04.R de la complementaria del 1ro de septiembre.
```
La base de datos **df** tiene las siguientes variables `r colnames(df)` y el valor mínimo de la variable **mpg** es `r min(df$mpg)`, y el modelo Mazda RX4 _`r df$i_mpg[df$modelo=="Mazda RX4"]`_

